//
//  AISBLString.h
//  AISbizlive
//
//  Created by Wachirawit on 2/21/2557 BE.
//  Copyright (c) 2557 promptnow. All rights reserved.
//

#import <Foundation/Foundation.h>
//Button
#define BUTTON_FACEBOOK_SIGNUP @"BUTTON_FACEBOOK_SIGNUP"
#define BUTTON_SIGNUP @"BUTTON_SIGNUP"
#define BUTTON_SIGNIN @"BUTTON_SIGNIN"
#define BUTTON_RESEND_EMAIL @"BUTTON_RESEND_EMAIL"
#define BUTTON_RESEND_OTP @"BUTTON_RESEND_OTP"
#define BUTTON_DONE @"BUTTON_DONE"
#define BUTTON_TERM @"BUTTON_TERM"
#define BUTTON_POLICY @"BUTTON_POLICY"
#define BUTTON_SIGNIN_FORGET @"BUTTON_SIGNIN_FORGET"
#define BUTTON_SIGNIN_SIGNIN @"BUTTON_SIGNIN_SIGNIN"

//Navigation Header
#define HEADER_FORGET @"HEADER_FORGET"
#define HEADER_SIGNIN @"HEADER_SIGNIN"
#define HEADER_EMAIL @"HEADER_EMAIL"
#define HEADER_OTP @"HEADER_OTP"
#define HEADER_SIGNUP @"HEADER_SIGNUP"
#define HEADER_TERM @"HEADER_TERM"
#define HEADER_POLICY @"HEADER_POLICY"

//Text Field Placehoder
#define PLACEHODER_SIGNIN_EMAIL @"PLACEHODER_SIGNIN_EMAIL"
#define PLACEHODER_SIGNIN_PASSWORD @"PLACEHODER_SIGNIN_PASSWORD"
#define PLACEHODER_SIGNUP_CONFIRMPASSWORD @"PLACEHODER_SIGNUP_CONFIRMPASSWORD"
#define PLACEHODER_SIGNUP_PASSWORD @"PLACEHODER_SIGNUP_PASSWORD"
#define PLACEHODER_SIGNUP_PHONE @"PLACEHODER_SIGNUP_PHONE"
#define PLACEHODER_SIGNUP_EMAIL @"PLACEHODER_SIGNUP_EMAIL"
#define PLACEHODER_SIGNUP_FULLNAME @"PLACEHODER_SIGNUP_FULLNAME"
#define PLACEHODER_EMAIL @"PLACEHODER_EMAIL"
#define PLACEHODER_OTP @"PLACEHODER_OTP"
#define PLACEHODER_FORGET @"PLACEHODER_FORGET"

//Label
#define LABEL_EMAIL @"LABEL_EMAIL"
#define LABEL_OTP @"LABEL_OTP"
#define LABEL_FORGET @"LABEL_FORGET"
#define LABEL_SIGNUP_EMAIL @"LABEL_SIGNUP_EMAIL"
#define LABEL_SIGNUP_PHONE @"LABEL_SIGNUP_PHONE"
#define LABEL_SIGNUP_PASSWORD @"LABEL_SIGNUP_PASSWORD"
#define LABEL_SIGNUP_CONFIRMPASSWORD @"LABEL_SIGNUP_CONFIRMPASSWORD"
#define LABEL_SIGNUP_TERM_POLICY @"LABEL_SIGNUP_TERM_POLICY"

@interface AISBLString : NSObject
+(NSString*)defaultString:(NSString*)key;
@end
